# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 43c1d804632051e3bc62746e3f2d345b6e337ada580384a978d0612f0ae44131dd6f214f17a4ee602da361ba5bea947e1b0cd7ce7fcfc623394cbc655ae3a1c0

test:
  secret_key_base: 088e616b49e4dca528078f259fee3d8fc334d8fdd5344482a93f8a9af65597a8f4996723a7e85601f03367139aedec77d35fe92576f84b3f30167cecb4d64188

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
