# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d3884b0f8df2f7bc8bcc8a83404ff46428218a1c79bc85d40fb98cce27bcd3f472902837880498aaa915e6394a682e78cf7dfd5998cb2c6c176f31f91dec60c6

test:
  secret_key_base: 4130d96de589e2ef413cec356ca42bb80900d6d85d8f6306962a6763b20094a97eedc73b0f5be0ae9b85390deb1f6a2da5807819229fe481e9b095dd586410b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
